Import modules.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

Define $f(x)$ in code.

In [2]:
def f(x):
    return 2*np.sin(x) + 3*(2.0**x) + 3*x

Make sure our function runs.

In [3]:
print(f(2))

19.818594853651362


Create the range of $x$ values we want to evaluate our function on.

In [4]:
x_range = np.arange(-2, 3).reshape(-1, 1)
print(x_range)

[[-2]
 [-1]
 [ 0]
 [ 1]
 [ 2]]


Evaluate the function on our range and assign to the variable `y`.

In [5]:
y = f(x_range)
print(y)

[[-7.06859485]
 [-3.18294197]
 [ 3.        ]
 [10.68294197]
 [19.81859485]]


Create the $sin(x)$ column of our basis expantion.

In [6]:
x_sin = np.sin(x_range).reshape(-1, 1)
print(x_sin)

[[-0.90929743]
 [-0.84147098]
 [ 0.        ]
 [ 0.84147098]
 [ 0.90929743]]


Create the $2^x$ column of our basis expansion.

In [7]:
x_2exp = (2.0 ** x_range).reshape(-1, 1)
print(x_2exp)

[[0.25]
 [0.5 ]
 [1.  ]
 [2.  ]
 [4.  ]]


Compile (stack) our columns into one single matrix `X` and ensure its dimensions (`shape`) correspond to the matrix we want.

In [8]:
X = np.hstack((x_sin, x_2exp, x_range))
print(X)
print(X.shape)

[[-0.90929743  0.25       -2.        ]
 [-0.84147098  0.5        -1.        ]
 [ 0.          1.          0.        ]
 [ 0.84147098  2.          1.        ]
 [ 0.90929743  4.          2.        ]]
(5, 3)


Calculate our coefficients for `b`.

In [9]:
b = np.linalg.lstsq(X, y)[0]
print(b)

[[2.]
 [3.]
 [3.]]


C:\Users\freez\AppData\Local\Temp\ipykernel_21304\1488620218.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  b = np.linalg.lstsq(X, y)[0]


Compare the values in `X @ b` ($Xb$) to the values in `y`.

In [10]:
print(X @ b)
print(y)
print((X @ b) - y)

[[-7.06859485]
 [-3.18294197]
 [ 3.        ]
 [10.68294197]
 [19.81859485]]
[[-7.06859485]
 [-3.18294197]
 [ 3.        ]
 [10.68294197]
 [19.81859485]]
[[ 7.10542736e-15]
 [ 4.88498131e-15]
 [-8.88178420e-16]
 [-7.10542736e-15]
 [-7.10542736e-15]]


Perform the regression using functions from `scikit-learn`.

In [11]:
reg = LinearRegression()
mod = reg.fit(X, y)

View our coefficients.

In [12]:
print(mod.coef_)

[[2. 3. 3.]]


Compare our model's predictions to our ground truth in `y`.

In [13]:
print(mod.predict(X))
print(y)
print(mod.predict(X) - y)

[[-7.06859485]
 [-3.18294197]
 [ 3.        ]
 [10.68294197]
 [19.81859485]]
[[-7.06859485]
 [-3.18294197]
 [ 3.        ]
 [10.68294197]
 [19.81859485]]
[[-7.10542736e-15]
 [-4.88498131e-15]
 [ 0.00000000e+00]
 [ 3.55271368e-15]
 [ 7.10542736e-15]]
